### ISSUE TITLE
dependencies should use exact version numbers

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-transport#103]
as per main Seneca; also versions need to be same as main Seneca

**Comment by mihaidma** [comment]
@rjrodger what do you think about the following approach at plugins:
- for **dependencies** allow patch, example 1.2.x,
- for **devDependenices** (used for tests) we allow patch and minor: 1.x.x,
- use specific version for cases like a specific store spec `"seneca-store-test": "1.0.0"`

Should we allow some freedom at least in dev dependencies? (maintenance reasons)

a sample from a plugin:

```
  "dependencies": {
    "lodash": "4.14.x",
    "node-uuid": "1.4.x",
    "nosj": "1.0.x",
    "redis": "2.5.x"
  },
  "devDependencies": {
    "code": "1.x.x",
    "eslint-config-seneca": "1.x.x",
    "eslint-plugin-hapi": "4.x.x",
    "eslint-plugin-standard": "1.x.x",
    "lab": "6.x.x",
    "seneca": "plugin",
    "seneca-entity": "1.x.x",
    "seneca-store-test": "1.0.0",
...
```

**Comment by mihaidma** [comment]
We proceeded with having dependencies as **fixed version** and the **same version** as Seneca. Example;
```
  "dependencies": {
    "lodash": "4.6.0",
    "node-uuid": "1.4.7",
    "nosj": "1.0.1",
    "redis": "2.6.2"
  },
```

On devDependencies kept x for lint, lab, coveralls and put fixed version for the others:

```
"devDependencies": {
    "code": "1.5.0",
    "docco": "0.7.0",
    "eslint-config-seneca": "1.x.x",
    "eslint-plugin-hapi": "4.x.x",
    "eslint-plugin-standard": "1.x.x",
    "lab": "6.2.x",
    "seneca": "plugin",
    "seneca-entity": "1.2.0",
    "seneca-store-test": "1.0.0",
    "coveralls": "2.x.x"
  },
```

**Comment by mcdonnelldean** [comment]
@mihaidma Yes let's go with this. Explicit pinning will kill our automation. Your thoughts above strike a nice balance between maintenance and stability.
