### ISSUE TITLE
Skipped tcp reconnect test fails on 1.x.x

### ISSUE THREAD

**Issue by thekemkid** [senecajs/seneca-transport#108]
That test is now at a state where it always will pass on v2.x.x, however on v1.x.x there is a weird error where the tcp port is being assigned at random when it explicitly specified.

In node v6 seneca seems to not be able to handle it at all and fails completely, not even assigning a random port.

**Comment by mcdonnelldean** [comment]
@thekemkid Let's skip this test on 1.x but run it for 2.x and higher. I'll go back and look into 1.x post 3 release and see if I can fix it.
