### ISSUE TITLE
Reconnect messages duplication

### ISSUE THREAD

**Issue by dgonzalez** [senecajs/seneca-transport#114]
This issue is related to #91.
# Description

When using `tcp` as transport, if the client is up and the sever restarts all the messages are repeated. 

The code to reproduce it is the following:

_client.js_

```
'use strict';

var seneca = require('seneca');

var service = seneca();

service.client({
    type: 'tcp',
    port: 12345,
    host: '0.0.0.0',
    pin: 'role:foo'
});

service.act({
    role: 'foo',
    cmd: 'bar',
    name: 'one',
}, function(err, res) {
    console.log(res, Date.now());
});

service.act({
    role: 'foo',
    cmd: 'bar',
    name: 'two',
}, function(err, res) {
    console.log(res, Date.now());
});
```

_server.js_

```
var seneca = require('seneca');

var service = seneca();

service.add({
    role: 'foo',
    cmd: 'bar'
}, function(args, cb) {
    console.log(args.name, Date.now(), args.meta$.id);
    cb(null, { test:123, name: args.name });
} )


service.listen({
    type: 'tcp',
    port: 12345,
    host: '0.0.0.0'
});
```

Run server.js in one terminal and client.js in another. If server.js gets restarted (ctrl-c and relaunch).

It does not happen with `http` transport but the behaviour is different: `http` disconnects as soon as the last `act` is sent whereas `tcp` keeps the connection alive preventing `client.js` to terminate.

As far as I can see, everything points to these lines (./lib/tcp.js):

```
 stream
          .pipe(parser)
          .pipe(msger)
          .pipe(stringifier)
          .pipe(stream)
```

If I read from the stream, all the messages are in there which suggests the client sending messages again as the server has restarted (lost the state).

This issue groups https://github.com/senecajs/seneca-transport/issues/91 and https://github.com/senecajs/seneca/issues/437.

**Comment by combsco** [comment]
I've recently experienced the same bug. If I bring down the service using seneca-transport tcp.

Client disconnects and does it's reconnect attempts. On successful reconnect the client is replaying the last action that was sent to this service.

**Comment by mcdonnelldean** [comment]
@combsco Yes, it is a known bug. We are going to rewrite the TCP driver soon enough.

**Comment by Mastermaulik** [comment]
I am experiencing the same issue as @combsco . Any updates on the issue, @mcdonnelldean ?

**Comment by wzrdtales** [comment]
@dgonzalez Is there any work from your side done on this? Since I do work on a new transport I would love to see if I could incorporate some of your thoughts.

**Comment by computerex** [comment]
So looks like this isn't getting any attention. This has been open for like over 2 years now.
