### ISSUE TITLE
Catchall in .client() and listen() not working

### ISSUE THREAD

**Issue by afoninsky** [senecajs/seneca-transport#117]
this happend only using transport plugin

``` javascript
const port = 8080
const server = require('seneca')()
const client = require('seneca')().client({ port })


server.add('role:somerole, cmd:remove', (message, done) => done())
server.add('role:somerole, cmd:anyothercommand', (message, done) => done())
server.listen(port)

client.act('role:somerole, cmd:remove', (err, res) => {
  if (err) {
    return console.log('WOOT?', err.message)
  }
  console.log('everything is fine - remove command is catched')
})

client.act('role:somerole, cmd:anyothercommand', (err, res) => {
  if (err) { throw err }
  console.log('everything is fine - other command is catched')
})
```

expected output:

```
everything is fine - remove command is catched
everything is fine - other command is catched
```

actual output:

```
WOOT? seneca: No matching action pattern found for { role: 'somerole', cmd: 'remove' }, and no default result provided (using a default$ property).
everything is fine - other command is catched
```

senecajs v. 2.1.0
node v. 6.1.0

**Comment by mcdonnelldean** [comment]
@afoninsky interesting. It looks like there is something up with specific `cmd:~` patterns. I'll dig deeper. 

@mihaidma @rjrodger you should be aware of this.

This code works:

```js
'use strict'

const port = 8080
const Seneca = require('seneca')

Seneca()
  .add('role:foo,cmd:make', (message, done) => done())
  .add('role:foo,cmd:add', (message, done) => done())
  .listen(port)

Seneca()
  .client({port: port})
  .act('role:foo,cmd:add', (err, res) => {
    if (err) console.log('Add Err', err.message)
    else console.log('everything is fine - add command is catched')
  })
  .act('role:foo,cmd:make', (err, res) => {
    if (err) console.log('Remove Err', err.message)
    else console.log('everything is fine - make command is catched')
  })
```

If you change either command to `cmd:remove` or `cmd:save` the automatic client pin will fail. 

However, if you explicitly pin out it works as expected. See code below,

```js
'use strict'

const port = 8080
const Seneca = require('seneca')

Seneca()
  .add('role:foo,cmd:save', (message, done) => done())
  .add('role:foo,cmd:remove', (message, done) => done())
  .listen(port)

Seneca()
  .client({port: port, pin: 'role:foo'})
  .act('role:foo,cmd:save', (err, res) => {
    if (err) console.log('Add Err', err.message)
    else console.log('everything is fine - save command is catched')
  })
  .act('role:foo,cmd:remove', (err, res) => {
    if (err) console.log('Remove Err', err.message)
    else console.log('everything is fine - remove command is catched')
  })
```

My assumption is there is a prior or default knocking about causing this.

**Comment by rjrodger** [comment]
@afoninsky Could run both tests with --seneca.log.all and post here thanks

**Comment by afoninsky** [comment]
https://gist.github.com/afoninsky/71236f2743995b6560904f4cd94823f0 - bug
https://gist.github.com/afoninsky/a79ec108020ef368150f24abfceaee21 - success
you're welcome

btw, why don't you use https://www.npmjs.com/package/debug ?

**Comment by rjrodger** [comment]
First inspection indicates that client without a pin is not acting as a catchall for patterns that are not found locally. Workaround is to specify pin, as you noted.

We need to consider this more deeply wrt catchall behavior and determining what is correct in this case.

**Comment by afoninsky** [comment]
senecajs v. 3.0.0 - looks ok

**Comment by mcdonnelldean** [comment]
@afoninsky Is this now working for you? I ask because we have, https://github.com/senecajs/seneca/issues/518 which seems to be the same issue as this.

**Comment by afoninsky** [comment]
as i mention before - everything is ok in 3.0.0
should i perform additional testing? if "no" - feel free to close this issue, thank you for your support
