### ISSUE TITLE
seneca.make$ is not a function in transport-utils.js

### ISSUE THREAD

**Issue by iamNoah1** [senecajs/seneca-transport#135]
Hey guys,

transport-utils.js seems to have problem while responding with an entity created with the Seneca Data Entity API. It tries to invoke seneca.make$(raw) in [line 487](https://github.com/senecajs/seneca-transport/blob/master/lib/transport-utils.js#L487) and crashes with the following stracktrace (at least for me).  

`
TypeError: seneca.make$ is not a function
    at internals.Utils.handle_entity (/Users/noa/Desktop/Workspace/stash/seneca_playground/node_modules/seneca-transport/lib/transport-utils.js:487:19)
    at internals.Utils.handle_response (/Users/noa/Desktop/Workspace/stash/seneca_playground/node_modules/seneca-transport/lib/transport-utils.js:82:19)
    at /Users/noa/Desktop/Workspace/stash/seneca_playground/node_modules/seneca-transport/lib/http.js:148:25
...
`

Some additional Stuff

Server:

``` javascript
var seneca = require('seneca')()

seneca.use('basic')
.use('entity')

seneca.add('role: db,cmd: persist', (msg, reply) => {
  var movie = seneca.make('movie')
  movie.title = msg.title

  movie.save$(function(err, saved_movie){
    if(err){
      reply(err, null);
    } else {
      reply(null, saved_movie)
    }
  })
})

seneca.ready(function(){
  seneca.listen();
})
```

Client:

``` javascript
var seneca_client = require('seneca')().client();

seneca_client.act({role: 'db', cmd: 'persist', title: "blade2"}, function (err, result) {
  if (err) return console.error(err)
  console.log(result)
})
```

Package.json:

```
{
  "name": "seneca_playground",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "seneca": "^3.2.1",
    "seneca-basic": "^0.5.0",
    "seneca-entity": "^1.3.0",
    "seneca-mem-store": "^0.6.0",
    "seneca-mongo-store": "^1.1.0"
  }
}

```

It would be nice if you could verify this. Thank you 

Cheers 
Noah

**Comment by jeromevalentin** [comment]
I faced the same issue, and as workaround I'm cleaning my entities prior to send them remotely. As you can see below:

```javascript
seneca.add('role: db,cmd: persist', (msg, reply) => {
  var movie = seneca.make('movie')
  movie.title = msg.title

  movie.save$(function(err, saved_movie){
    if(err){
      reply(err, null);
    } else {
      reply(null, seneca.util.clean(saved_movie))
    }
  })
})
```
"Clean" removes all $ properties/functions from the entity, and the client is no more trying to call make$.

Hope this helps,
Regards,
Jérôme

**Comment by MeBNoah** [comment]
Thanks for the workaround ... worked like a charm 👍

**Comment by MikeLindenau** [comment]
I assume this is not desired behavior?

**Comment by jeromevalentin** [comment]
FMHO this kind of behavior is application dependant and the choice to send entity remotely must be left to the developer. By the way I don't have tested it, but I'm not sure what will be the behavior when using an entity remotely:
* Should an update query alter the remote storage? 
* Should that replicate the entity locally on a local storage?
... 
Definitely this is an application developer choice, and the framework should not try to handle that.

**Comment by killerspaz** [comment]
If I'm understanding correctly, the framework is trying to serialize and deserialize an entity, but the entity isn't defined in the remote system?

Should the framework maybe indicate more about an entity not being loaded instead of an arbitrary error?

**Comment by rjrodger** [comment]
workaround is load `seneca-entity` plugin
