### ISSUE TITLE
Communication between Seneca microservices

### ISSUE THREAD

**Issue by daemons88** [senecajs/seneca-transport#147]
Hi, i am new with this and try to make a server and client microservices with seneca all in the same pc using localhost, i can access the seneca add by browser or executing a act in the same file but when i try to get the response for other seneca microservice i get timeout or No matching action pattern found for...

this is my code in **"Server"**:

//index

`
"use strict";

const Seneca = require('seneca');
const SenecaWeb = require('seneca-web');
const Express = require('express');
const Routes = require('./routes');
const ProvincePlugin = require('./provincePlugin');
const seneca = Seneca();

var config = {
    routes: Routes,
    context: Express(),
    adapter: require('seneca-web-adapter-express')
};

seneca.use(ProvincePlugin)
    .use(SenecaWeb, config)
    .ready(() => {
        const app = seneca.export('web/context')();
        app.listen({
            port: '4000',
            host: 'localhost'
        });
        console.log('server started on: 4000');
    });
`

//provincePlugin.js

`
"use strict";

module.exports = function provincePlugin(options) {

    var seneca = this;

    seneca.add({
        area: "province",
        action: "test"
    }, function(req, done) {
        done(null, {
            result: "Hello World From Seneca"
        });
    });
}
`

//routes.js

`
"use strict";

module.exports = [{
    prefix: '/provinces',
    pin: 'role:web,area:province,action:*',
    map: {
        test: {
            GET: true
        }
    }
}];
`

Now the **"Client"**:
//Api
`
"use strict";

const Seneca = require('seneca');
const SenecaWeb = require('seneca-web');
const Express = require('express');
const Routes = require('./routes');
const ProvincePlugin = require('./provinceSeneca');
const seneca = Seneca();

var config = {
  routes: Routes,
  context: Express(),
  adapter: require('seneca-web-adapter-express')
};

seneca.use(ProvincePlugin)
  .use(SenecaWeb, config)
  .ready(() => {
    const app = seneca.export('web/context')();
    app.listen({
      port: '3500',
      host: 'localhost'
    });
    console.log('server started on: 3500');

    seneca.act('role:web,area:ui,action:test', console.log);
  });
`
//provinceSeneca
`
"use strict";

var senecaProvince = require("seneca")().client({
  port: '4000',
  host: 'localhost',
  pin: 'role:web' 
});

module.exports = function provinceSeneca(options) {

  var seneca = this;

  seneca.add({
    area: "ui",
    action: "test"
  }, function(args, done) {
    senecaProvince.act({
      area: "province",
      action: "test"
    }, function(err, result) {
      done(err, result);
    });
  });
}
`
//routes
`
"use strict";

module.exports = [{
  prefix: '/api',
  pin: 'role:web,area:ui,action:*',
  map: {
    test: {
      GET: true
    }
  }
}];
`

In the client, provinceSeneca when do: require("seneca")().client...
If i add pin: 'role:web'  i get No matching action pattern found for... 
If i remove that i get timeout...

i dont find the problem/solution for this in documentation, please can help me?

Regards!!

**Comment by rjrodger** [comment]
Thanks for your question! Please use stackoverflow for Seneca usage questions, and Github for bug reports and feature discussions. Seneca on stackoverflow: https://stackoverflow.com/questions/tagged/seneca
