### ISSUE TITLE
tcp transport crash on disconnect

### ISSUE THREAD

**Issue by calibermind** [senecajs/seneca-transport#149]
When the connection is empty, the _.find will return **undefined** therefore the following will cause a crash: 
        _.find(connections, { clientOptions: clientOptions }).setup = false

this is line 161 seneca-transport/lib/tcp.js.

one solution is -

if (connections.length !== 0 ){
             _.find(connections, { clientOptions: clientOptions }).setup = false
          }

**Comment by friedemannsommer** [comment]
This issue refers to #144
