### ISSUE TITLE
Support multiple arguments

### ISSUE THREAD

**Issue by nfantone** [senecajs/seneca-transport#152]
_From https://github.com/senecajs/seneca-amqp-transport/issues/78_.

Original author: @bra1n

Example:
```js
// listener
require('seneca')().use('seneca-amqp-transport')
.add({a:1, b:2}, function (msg, reply) {
    reply(null, {z: msg.z}, 123) // <--- 3 arguments here
}).listen({type: 'amqp', pin: 'a:1,b:2', url: 'amqp://guest:guest@localhost:5672/'});

// client
require('seneca')().use('seneca-amqp-transport')
.client({type: 'amqp', pin: 'a:1,b:2', url: 'amqp://guest:guest@localhost:5672/'})
.act('a:1,b:2,z:9', console.log); // should log all arguments
```

Expected output:
```
null { z: 9 } 123
```

Actual output:
```
null { z: 9 } { id: 'wmkrp7ebp8yd/tjrznrcu10hm',
  accept: 'tkxxb46prhmh/1487592318189/4167/3.3.0/-',
  track: [ '2j0b5xk44e4z/1487592318564/4167/3.3.0/-' ],
  time:
   { client_sent: 1487592318854,
     listen_recv: 1487592318885,
     listen_sent: 1487592318893,
     client_recv: 1487592318896 } }
```

Seneca supports more than 2 arguments in act callbacks since [#340](https://github.com/senecajs/seneca/issues/340).

----

This was brought to my attention over at [seneca-amqp-transport](https://github.com/senecajs/seneca-amqp-transport) and ended up finding out that seneca-transport does not handle arguments other the very first on `.act` callbacks. This can be seen in [this line](https://github.com/senecajs/seneca-transport/blob/master/lib/transport-utils.js#L262) of `transport-utils.js`. In the scenario described by @br1an, there would be a second, omitted argument, next to `out`, with value `123`.

**Comment by bra1n** [comment]
Bump

**Comment by nfantone** [comment]
@rjrodger Any ideas on this?

**Comment by nfantone** [comment]
@rjrodger So... not working on this anymore? Apologies for bothering you, if that's the case. Should I ping somebody else?

**Comment by rjrodger** [comment]
@nfantone - sorry -  this is by design - responses should be a single JSON object
