### ISSUE TITLE
firebase transport

### ISSUE THREAD

**Issue by yieme** [senecajs/seneca-transport#16]
Is it possible to use firebase as a transport?

[Trello Card](https://trello.com/c/crOXwSUz/34-seneca-transport-firebase-transport)

**Comment by rjrodger** [comment]
anything can be used as transport - see for example: https://github.com/rjrodger/seneca-redis-transport
what is your use-case?

**Comment by geek** [comment]
Closing for now, @yieme please reopen if there is still an outstanding question
