### ISSUE TITLE
FAQ: act cross server

### ISSUE THREAD

**Issue by freeweed** [senecajs/seneca-transport#163]
Hi every one.

It's possible to act from one service (e.g. localhost) to another service (e.g. in digitalocean) that stay in another server and behind authentication policy, so it's require token (I solve that by modify header in seneca-transport node_modules). I already try to set host, path and port in seneca listen but it's throw error seneca: listen EADDRNOTAVAIL.

Here's my question is

It's possible or not? and how.
It's have better way to set token?
please help!
thank.

**Comment by rjrodger** [comment]
best practice here is really to use a service mesh or a suitable proxy
