### ISSUE TITLE
Non-seneca TCP clients support is missing (telnet/nc)

### ISSUE THREAD

**Issue by dkulichkin** [senecajs/seneca-transport#24]
No way to leverage telnet/nc connections within current implementation. Request should be extended with seneca transport protocol fields (id, kind), similarly to curl client

[Trello Card](https://trello.com/c/SWFrKfMq/36-seneca-transport-non-seneca-tcp-clients-support-is-missing-telnet-nc)

**Comment by rjrodger** [comment]
It is possible to make action calls over telnet - can you provide more details if what you are trying to do?

Here's what I did:

```sh
$ cd seneca-transport/test
$ node service-foo.js tcp
```
and then telnet:
```sh
$ telnet localhost 10201
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
{"id":1,"kind":"act","act":{"foo":1}}
{"id":1,"kind":"res","accept":"98lb4s1pg44u/1433948418085/12583/-","time":{"client_sent":0,"listen_recv":1433948455864,"listen_sent":1433948455864},"res":{"s":"1-undefined"}}
```

**Comment by rjrodger** [comment]
Just looking your fork - can you explain your use-case - looks interesting!

**Comment by mcdonnelldean** [comment]
Going to close, @dkulichkin If you want to discuss feel free to open.
