### ISSUE TITLE
client() or other ways to discover microservices over network

### ISSUE THREAD

**Issue by vovantigo** [senecajs/seneca-transport#31]
Hi!
In readme.md of seneca-transport's I have found such phrase as "...single client definition will send all unrecognized action patterns over the network..." other hints that points on fact that client(*without parameters but timeout*) first tries to discover service on the localhost, and than goes over the network.

But when I try to run code, I have found that client(without parameters) works properly and can discover microservice only when it runs in the same node process listen() does. If I separate them into different node process (not to mention run them on different virtual machines) only client(...) with directly stated host and port works correctly. In all other cases I've got Error like: seneca: Action  failed: [TIMEOUT]...

I've tried to increase timeout to 10 min and more on client, but it doesn't help.

Could you clarify this moment please? Are client() without directly stated host and port able to discover microcervices over network?

If not, what way of discovering microservices could you advice, providing they are hosted on dynamically created virtual machines (for instance by means of AWS autoscaling group) and we cannot know host IPs in advance.

[Trello Card](https://trello.com/c/dZz4qaxx/38-seneca-transport-client-or-other-ways-to-discover-microservices-over-network)

**Comment by rjrodger** [comment]
Take a look at https://github.com/rjrodger/seneca-mesh :)
