### ISSUE TITLE
Any plans related to loadbalance-transport?

### ISSUE THREAD

**Issue by vovantigo** [senecajs/seneca-transport#32]
Hi,

unfortunately, such useful tool as loadbalance-transport (there is a link in readme) is outdated at the moment and doesn't work properly. Is there any plans to repair/reimplement it? May be any advice about third-party implementation?

[Trello Card](https://trello.com/c/NA4PYsG7/39-seneca-transport-any-plans-related-to-loadbalance-transport)

**Comment by rjrodger** [comment]
YES! This has been replaced by https://github.com/rjrodger/seneca-balance-client which is way way way better :)
