### ISSUE TITLE
Tests are red on Windows

### ISSUE THREAD

**Issue by piccoloaiutante** [senecajs/seneca-transport#42]
running:

./node_modules/.bin/mocha test/*.test.js --timeout 3000

gives an output with few broken tests while the same command on mac gives all green lights.

https://trello.com/c/gE28GVzi/117-seneca-trasport-tests-are-red-on-windows

**Comment by rjrodger** [comment]
possibly due to #37 ?

**Comment by geek** [comment]
Fixed by moving to lab and removing test script

**Comment by piccoloaiutante** [comment]
:+1:
