### ISSUE TITLE
Add a client-id header to client http requests on the web transport

### ISSUE THREAD

**Issue by baldmountain** [senecajs/seneca-transport#68]
We are going to route seneca requests through a load balancer. It would be nice to be able to monitor requests using a service specific header to identify traffic/requests coming from each service. Being able to specify a header like:

"client-id": "my-service"

as an option to the web transport would be helpful.

**Comment by geek** [comment]
Here is one option for reporting seneca stats: https://github.com/senecajs/seneca-msgstats

**Comment by geek** [comment]
Fixed by https://github.com/senecajs/seneca-transport/pull/81
