### ISSUE TITLE
fix:  tcp port server crash  when http.request to this port

### ISSUE THREAD

**Issue by peterli888** [senecajs/seneca-transport#69]
seneca.listen({type:'tcp',port:3000});
curl "http://localhost:3000" will crash the server

fix: seneca-transport // tcp.js
before:   "parser.on('data', function (data) "
add:
parser.on('error', function (error) {
   connection.end(); 			
});

**Comment by geek** [comment]
@peterli888 looks reasonable, can you submit a pull request?

**Comment by geek** [comment]
Fixed by https://github.com/senecajs/seneca-transport/commit/666e08f2967e65aedb3cc4e9266c599040cc7704
