### ISSUE TITLE
one way communication

### ISSUE THREAD

**Issue by longweiquan** [senecajs/seneca-transport#70]
Hello Seneca Team,

Can seneca-transport support the one-way (fire-and-forget) communication without triggering timeout exception for response ? Precisely, I want to implement one-way communication transport based on amqp, how can I do it ?

Thank you in advance.

**Comment by geek** [comment]
If you don't expect a result you can leave out the callback when executing an action. Here are tests that demonstrate this: https://github.com/senecajs/seneca/blob/master/test/seneca.test.js#L735-L749

Another option, if you don't care if the action even exists, is to pass `fatal$: false` when calling `seneca.act`
