### ISSUE TITLE
Can Seneca be a web server as well?

### ISSUE THREAD

**Issue by rodryquintero** [senecajs/seneca-transport#77]
I want to use Seneca for api endpoints but I would like to know if it can also serve static content (index.html with js scripts for the client app) or do I need to use something else for serving static content.

I would like to use port 80 for everything.

**Comment by geek** [comment]
https://github.com/senecajs/seneca-web will help with exposing seneca actions as endpoints.  For static assets you will want to use `inert` for hapi or the static file server for express.
