### ISSUE TITLE
How to pass internals as options to transport

### ISSUE THREAD

**Issue by manoj150283** [senecajs/seneca-transport#84]
I am looking for some way to pass internals as options to transport. Default host configured inside internal is 0.0.0.0. But when I am running inside container, it is not working and giving error. When I changed the value to hard coded value of my host, it is working fine. Is there any way to pass host defined inside internal as options.

Regards,
- Manoj

**Comment by geek** [comment]
@manoj150283 sorry for the long delay in a response... 

You can pass any of the options in https://github.com/senecajs/seneca-transport/blob/master/transport.js#L26-L46 when you `use` the transport plugin from seneca.

Here is an example of changing the `check.own_message` option.

```js
const Seneca = require('seneca');

const option = { 
  plugin: { 
    transport: { 
      check: { 
        own_message: false 
      }
    } 
  } 
};
const seneca = new Seneca(option);
```
