### ISSUE TITLE
Tests failing when using Seneca@1.4.0 and Node@5

### ISSUE THREAD

**Issue by shanel262** [senecajs/seneca-transport#93]
The tests are failing when Node@5 is used, giving an error that the module 'wreck' cannot be found. The tests are also failing when using Seneca@1.4.0 with all versions of node.
https://travis-ci.org/senecajs/seneca-transport/builds/125606868

**Comment by shanel262** [comment]
This module is now being tested with Node@6 and the tests are failing because it cannot find module 'Wreck' https://travis-ci.org/senecajs/seneca-transport/builds/129086855

**Comment by mcdonnelldean** [comment]
Landed in #101
